import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Language = "es" | "en";

const translations = {
  es: { home: "Inicio", howItWorks: "Cómo funciona", aiRobot: "Robot IA", performance: "Rendimientos", plans: "Planes", security: "Seguridad", login: "Iniciar sesión", register: "Crear cuenta", startNow: "Empezar ahora", discover: "Descubrir TradeNova AI", automatedTrading: "Trading automatizado", aiAnalysis: "Análisis IA", monitoring247: "Monitoreo 24/7", language: "Idioma", spanish: "Español", english: "English" },
  en: { home: "Home", howItWorks: "How it works", aiRobot: "AI Robot", performance: "Performance", plans: "Plans", security: "Security", login: "Sign in", register: "Create account", startNow: "Get started", discover: "Discover TradeNova AI", automatedTrading: "Automated trading", aiAnalysis: "AI analysis", monitoring247: "24/7 monitoring", language: "Language", spanish: "Español", english: "English" },
} as const;

type TranslationKey = keyof typeof translations.es;
type I18nContextValue = { language: Language; setLanguage: (language: Language) => void; t: (key: TranslationKey) => string };
const I18nContext = createContext<I18nContextValue | null>(null);

const uiTranslations: Record<string, string> = {
  "Dashboard":"Dashboard","Operaciones":"Operations","Portafolio":"Portfolio","Fondos":"Funds","Notificaciones":"Notifications","Perfil":"Profile","Preferencias":"Preferences","Administración":"Administration","Panel de control":"Control panel","Modo DEMO · datos de demostración":"DEMO mode · demonstration data","Sistema operativo":"System operational","Navegación":"Navigation","Cerrar sesión":"Sign out","Cuenta activa":"Active account","Usuario":"User",
  "Datos de demostración":"Demo data","ACTIVO":"ACTIVE","Activo":"Active","tendencia detectada":"trend detected","Señales":"Signals","Volatilidad":"Volatility","Riesgo":"Risk","MEDIO":"MEDIUM","Análisis de mercado":"Market analysis","Detección de señales":"Signal detection","Gestión de riesgo":"Risk management","Modos de operación":"Operating modes","Multi-mercado":"Multi-market","Automatización 24/7":"24/7 automation",
  "Robot IA":"AI Robot","Configuración del Robot IA":"AI Robot Configuration","Configura la estrategia y los límites de la simulación.":"Configure the strategy and simulation limits.","Estrategia":"Strategy","Equilibrada":"Balanced","Conservadora":"Conservative","Tendencia":"Trend","Nivel de riesgo":"Risk level","Bajo":"Low","Medio":"Medium","Alto":"High","Capital asignado (USD)":"Allocated capital (USD)","Modo":"Mode","Mercados":"Markets","Activar robot":"Activate robot","Solo se ejecuta como simulación mientras esté en DEMO.":"It only runs as a simulation while in DEMO.","Guardar configuración":"Save configuration","Guardando...":"Saving...","Activar DEMO":"Activate DEMO","Detener":"Stop","Configuración guardada.":"Configuration saved.","Robot activado en modo DEMO.":"Robot activated in DEMO mode.","Selecciona al menos un mercado.":"Select at least one market.","El modo LIVE todavía no está disponible. Cambia a DEMO para activar el robot.":"LIVE mode is not available yet. Switch to DEMO to activate the robot.","El modo LIVE requiere una implementación de ejecución real y controles adicionales. Esta versión no ejecuta operaciones reales y no permite activar el robot en LIVE.":"LIVE mode requires real execution and additional controls. This version does not execute real trades and does not allow the robot to be activated in LIVE.",
  "Historial reciente de actividad del robot.":"Recent robot activity history.","Aún no hay operaciones":"There are no operations yet","Cuando el robot genere operaciones, aparecerán aquí con su resultado.":"When the robot generates operations, they will appear here with their results.","Activo":"Asset","Dirección":"Direction","Entrada":"Entry","Salida":"Exit","Tamaño":"Size","Estado":"Status","Abierta":"Open","Cerrada":"Closed",
  "Patrimonio":"Equity","Patrimonio actual":"Current equity","Capital invertido":"Invested capital","P&L acumulado":"Accumulated P&L","Rendimiento":"Performance","Resultado de hoy":"Today's result","P&L registrado en el portafolio.":"P&L recorded in the portfolio.","Total depositado":"Total deposited","Capital ingresado a la cuenta.":"Capital added to the account.","Vista consolidada de tu capital y resultados.":"Consolidated view of your capital and results.","Histórico de rendimiento":"Performance history","El gráfico histórico se habilitará cuando exista una serie temporal de rendimiento en Supabase. No se inventan datos históricos.":"The historical chart will be enabled when a performance time series exists in Supabase. No historical data is invented.","P&L de hoy":"Today's P&L","Resultado del día":"Today's result","P&L total":"Total P&L","Ganancia acumulada":"Accumulated gain","Depositado:":"Deposited:","Bienvenido de nuevo":"Welcome back","Este es el resumen de tu actividad de trading.":"Here is a summary of your trading activity.","Ver todas":"View all","Operaciones recientes":"Recent operations","Todavía no hay operaciones registradas.":"There are no recorded operations yet.","Accesos rápidos":"Quick access","Ver portafolio":"View portfolio","Mi perfil":"My profile","Portafolio conectado":"Connected portfolio","Modo DEMO activo":"DEMO mode active","Los indicadores proceden de tu registro de portafolio en Supabase.":"The metrics come from your portfolio record in Supabase.","Los valores mostrados son de demostración porque todavía no hay un portafolio asociado a esta cuenta.":"The values shown are for demonstration because this account does not have an associated portfolio yet.","Simulación":"Simulation",
  "Depositar fondos":"Deposit funds","Retirar fondos":"Withdraw funds","Importe (USD)":"Amount (USD)","Método":"Method","Destino":"Destination","Cuenta o wallet de destino":"Destination account or wallet","Solicitar depósito":"Request deposit","Solicitar retiro":"Request withdrawal","Historial de depósitos":"Deposit history","Historial de retiros":"Withdrawal history","Cargando…":"Loading…","Todavía no hay depósitos registrados.":"No deposits have been recorded yet.","Todavía no hay retiros registrados.":"No withdrawals have been recorded yet.","Por seguridad, verifica cuidadosamente el destino antes de solicitar un retiro.":"For security, carefully verify the destination before requesting a withdrawal.","Modo DEMO: estas solicitudes registran movimientos en Supabase, pero no procesan pagos reales ni transfieren fondos automáticamente.":"DEMO mode: these requests record movements in Supabase, but do not process real payments or transfer funds automatically.","Introduce un importe válido.":"Enter a valid amount.","Introduce importe y destino válidos.":"Enter a valid amount and destination.","Solicitud de depósito registrada.":"Deposit request recorded.","Solicitud de retiro registrada.":"Withdrawal request recorded.",
  "Alertas y novedades de tu cuenta.":"Alerts and updates from your account.","Marcar todas":"Mark all as read","Cerrar":"Close","Cargando notificaciones…":"Loading notifications…","No tienes notificaciones":"You have no notifications","Aquí aparecerán alertas importantes de TradeNova AI.":"Important TradeNova AI alerts will appear here.","Marcar como leída":"Mark as read","No fue posible cargar las notificaciones.":"Unable to load notifications.","No fue posible actualizar la notificación.":"Unable to update the notification.","No fue posible marcar todas como leídas.":"Unable to mark all as read.",
  "Perfil personal":"Personal profile","Administra exclusivamente tus datos personales, contacto y foto.":"Manage your personal information, contact details and photo.","Foto de perfil":"Profile photo","Subiendo...":"Uploading...","Cambiar foto":"Change photo","Nombre completo":"Full name","Correo electrónico":"Email","Teléfono":"Phone","País":"Country","Selecciona tu país":"Select your country","Dirección":"Address","Fecha de nacimiento":"Date of birth","Guardar perfil":"Save profile","Completa nombre, país y una fecha de nacimiento válida para mayores de 18 años.":"Complete your name, country and a valid date of birth for users over 18.","Perfil actualizado correctamente.":"Profile updated successfully.","Selecciona una imagen válida de máximo 5 MB.":"Select a valid image up to 5 MB.","Foto de perfil actualizada.":"Profile photo updated.","No se pudo subir la foto.":"The photo could not be uploaded.",
  "Preferencias":"Preferences","Configura la experiencia de Trade Nova AI. Esta página no contiene datos personales ni cambio de contraseña.":"Configure your Trade Nova AI experience. This page does not contain personal data or password changes.","Idioma":"Language","Moneda":"Currency","Tema":"Theme","Oscuro":"Dark","Claro":"Light","Sistema":"System","USD — Dólar":"USD — Dollar","BRL — Real":"BRL — Real","EUR — Euro":"EUR — Euro","Notificaciones por email":"Email notifications","Actualizaciones importantes de tu cuenta.":"Important updates from your account.","Notificaciones push":"Push notifications","Avisos en tiempo real cuando estén disponibles.":"Real-time alerts when available.","Alertas de riesgo":"Risk alerts","Cambios relevantes de riesgo y actividad.":"Relevant risk and activity changes.","Preferencias guardadas correctamente.":"Preferences saved successfully.","Guardar preferencias":"Save preferences","Português (Brasil)":"Português (Brasil)",
  "Seguridad de la cuenta":"Account security","Protege el acceso a tu cuenta. Esta página está dedicada exclusivamente a seguridad.":"Protect access to your account. This page is dedicated exclusively to security.","Contraseña":"Password","Gestionada de forma segura mediante Supabase Auth.":"Securely managed through Supabase Auth.","Autenticación de dos factores":"Two-factor authentication","Disponible para integración con MFA de Supabase.":"Available for integration with Supabase MFA.","Cambiar contraseña":"Change password","Nueva contraseña (mín. 8 caracteres)":"New password (min. 8 characters)","Confirmar nueva contraseña":"Confirm new password","Actualizar contraseña":"Update password","Actualizando...":"Updating...","La nueva contraseña debe tener al menos 8 caracteres.":"The new password must be at least 8 characters.","Las contraseñas no coinciden.":"Passwords do not match.","Contraseña actualizada correctamente.":"Password updated successfully.",
  "Inicia sesión para entrar a tu plataforma TradeNova AI.":"Sign in to access your TradeNova AI platform.","¿La olvidaste?":"Forgot it?","Mostrar contraseña":"Show password","Ocultar contraseña":"Hide password","Iniciando sesión...":"Signing in...","¿Aún no tienes una cuenta?":"Don't have an account yet?","Crea tu cuenta":"Create your account","Completa tus datos para comenzar tu experiencia con TradeNova AI.":"Complete your details to start your TradeNova AI experience.","Tu nombre completo":"Your full name","Te enviaremos un correo para confirmar tu cuenta.":"We'll email you to confirm your account.","Debes ser mayor de 18 años.":"You must be at least 18 years old.","Mínimo 8 caracteres":"Minimum 8 characters","Acepto los términos y condiciones y confirmo que tengo":"I accept the terms and conditions and confirm that I am","18 años o más":"18 years or older","Creando cuenta...":"Creating account...","¿Ya tienes una cuenta?":"Already have an account?","Selecciona tu país.":"Select your country.","La fecha de nacimiento es obligatoria.":"Date of birth is required.","Debes tener al menos 18 años para crear una cuenta.":"You must be at least 18 years old.","Debes aceptar los términos y condiciones para continuar.":"You must accept the terms and conditions to continue.","Cuenta creada. Revisa tu correo para confirmar tu dirección antes de iniciar sesión.":"Account created. Check your email to confirm your address before signing in.","Tu próxima generación de trading inteligente empieza aquí.":"Your next generation of intelligent trading starts here.","Accede a tu plataforma y gestiona tu experiencia TradeNova AI desde un solo lugar.":"Access your platform and manage your TradeNova AI experience from one place.","Volver al inicio":"Back to home",
  "Plan actual":"Current plan","Cambiar plan":"Change plan","Guardar":"Save","Cancelar":"Cancel","Editar":"Edit","Eliminar":"Delete","Actualizar":"Update","Volver":"Back","Sí":"Yes","No":"No","Pendiente":"Pending","pendiente":"pending","Aprobado":"Approved","Completado":"Completed","Rechazado":"Rejected","Cancelado":"Cancelled","Error":"Error","Inactivo":"Inactive",
};

function translateNodeText(root: Node, language: Language) {
  if (language !== "en") return;
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const nodes: Text[] = []; let node: Node | null;
  while ((node = walker.nextNode())) nodes.push(node as Text);
  for (const text of nodes) {
    const value = text.nodeValue ?? ""; const trimmed = value.trim(); if (!trimmed) continue;
    const translated = uiTranslations[trimmed];
    if (translated && translated !== trimmed) text.nodeValue = value.replace(trimmed, translated);
    else if (trimmed.startsWith("Hola, ")) text.nodeValue = value.replace(trimmed, `Hello, ${trimmed.slice(6)}`);
    else if (trimmed.startsWith("Depositado: ")) text.nodeValue = value.replace(trimmed, `Deposited: ${trimmed.slice(11)}`);
  }
}

function restoreSpanish(root: Node) {
  const reverse = new Map(Object.entries(uiTranslations).map(([es, en]) => [en, es]));
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT); const nodes: Text[] = []; let node: Node | null;
  while ((node = walker.nextNode())) nodes.push(node as Text);
  for (const text of nodes) { const value = text.nodeValue ?? ""; const trimmed = value.trim(); const spanish = reverse.get(trimmed); if (spanish) text.nodeValue = value.replace(trimmed, spanish); else if (trimmed.startsWith("Hello, ")) text.nodeValue = value.replace(trimmed, `Hola, ${trimmed.slice(7)}`); else if (trimmed.startsWith("Deposited: ")) text.nodeValue = value.replace(trimmed, `Depositado: ${trimmed.slice(11)}`); }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === "undefined") return "es";
    const stored = window.localStorage.getItem("tradenova-language");
    if (stored === "en" || stored === "es") return stored;
    return window.navigator.language.toLowerCase().startsWith("en") ? "en" : "es";
  });
  const setLanguage = (next: Language) => { setLanguageState(next); if (typeof window !== "undefined") window.localStorage.setItem("tradenova-language", next); };
  useEffect(() => { document.documentElement.lang = language; const apply = () => language === "en" ? translateNodeText(document.body, "en") : restoreSpanish(document.body); apply(); const observer = new MutationObserver(apply); observer.observe(document.body, { childList: true, subtree: true }); return () => observer.disconnect(); }, [language]);
  const value = useMemo<I18nContextValue>(() => ({ language, setLanguage, t: (key) => translations[language][key] }), [language]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
export function useLanguage() { const context = useContext(I18nContext); if (!context) throw new Error("useLanguage must be used inside LanguageProvider"); return context; }
export function LanguageSwitcher() { const { language, setLanguage, t } = useLanguage(); return <div className="flex items-center gap-1 rounded-lg border border-border bg-background p-1" aria-label={t("language")}><button type="button" onClick={() => setLanguage("es")} aria-pressed={language === "es"} className={`rounded-md px-2 py-1 text-xs font-semibold transition-colors ${language === "es" ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:text-foreground"}`}>ES</button><button type="button" onClick={() => setLanguage("en")} aria-pressed={language === "en"} className={`rounded-md px-2 py-1 text-xs font-semibold transition-colors ${language === "en" ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:text-foreground"}`}>EN</button></div>; }
