import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Eye, EyeOff, Loader2, Mail, Lock, User, Phone, MapPin, CalendarDays, Globe2 } from "lucide-react";
import { AuthShell } from "@/components/auth/AuthShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
import { countryOptions } from "@/lib/countries";
import { useLanguage } from "@/lib/i18n";

export const Route = createFileRoute("/register")({ component: RegisterPage });
function calculateAge(dateOfBirth: string) { const today = new Date(); const birth = new Date(`${dateOfBirth}T00:00:00`); let age = today.getFullYear() - birth.getFullYear(); const month = today.getMonth() - birth.getMonth(); if (month < 0 || (month === 0 && today.getDate() < birth.getDate())) age--; return age; }

function RegisterPage() {
  const navigate = useNavigate(); const { language } = useLanguage(); const en = language === "en";
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [phone, setPhone] = useState(""); const [country, setCountry] = useState(""); const [address, setAddress] = useState(""); const [dateOfBirth, setDateOfBirth] = useState(""); const [password, setPassword] = useState(""); const [accepted, setAccepted] = useState(false); const [show, setShow] = useState(false); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const maxBirthDate = useMemo(() => { const d = new Date(); d.setFullYear(d.getFullYear() - 18); return d.toISOString().slice(0, 10); }, []);
  const t = en ? { title:"Create your account", desc:"Complete your details to start your TradeNova AI experience.", name:"Full name", namePh:"Your full name", email:"Email address", emailPh:"you@email.com", emailHint:"We will send you an email to confirm your account.", phone:"Phone", phonePh:"+58 ...", country:"Country", countryPh:"Select your country", dob:"Date of birth", dobHint:"You must be 18 or older.", address:"Address", addressPh:"Street, number, city, state...", password:"Password", passwordPh:"Minimum 8 characters", show:"Show password", hide:"Hide password", terms:"I accept the terms and conditions and confirm that I am", age:"18 years or older", loading:"Creating account...", create:"Create account", already:"Already have an account?", login:"Sign in", countryErr:"Select your country.", dobErr:"Date of birth is required.", ageErr:"You must be at least 18 years old to create an account.", termsErr:"You must accept the terms and conditions to continue.", created:"Account created. Check your email to confirm your address before signing in." } : { title:"Crea tu cuenta", desc:"Completa tus datos para comenzar tu experiencia con TradeNova AI.", name:"Nombre completo", namePh:"Tu nombre completo", email:"Correo electrónico", emailPh:"tu@email.com", emailHint:"Te enviaremos un correo para confirmar tu cuenta.", phone:"Teléfono", phonePh:"+58 ...", country:"País", countryPh:"Selecciona tu país", dob:"Fecha de nacimiento", dobHint:"Debes ser mayor de 18 años.", address:"Dirección", addressPh:"Calle, número, ciudad, estado...", password:"Contraseña", passwordPh:"Mínimo 8 caracteres", show:"Mostrar contraseña", hide:"Ocultar contraseña", terms:"Acepto los términos y condiciones y confirmo que tengo", age:"18 años o más", loading:"Creando cuenta...", create:"Crear cuenta", already:"¿Ya tienes una cuenta?", login:"Iniciar sesión", countryErr:"Selecciona tu país.", dobErr:"La fecha de nacimiento es obligatoria.", ageErr:"Debes tener al menos 18 años para crear una cuenta.", termsErr:"Debes aceptar los términos y condiciones para continuar.", created:"Cuenta creada. Revisa tu correo para confirmar tu dirección antes de iniciar sesión." };
  async function handleRegister(event: React.FormEvent) { event.preventDefault(); setError(""); setMessage(""); if (!country) { setError(t.countryErr); return; } if (!dateOfBirth) { setError(t.dobErr); return; } if (calculateAge(dateOfBirth) < 18) { setError(t.ageErr); return; } if (!accepted) { setError(t.termsErr); return; } setLoading(true); const selectedCountry = countryOptions.find((item) => item.code === country); const { data, error } = await supabase.auth.signUp({ email: email.trim(), password, options: { data: { full_name: name.trim(), phone: phone.trim(), country, country_name: selectedCountry?.name ?? country, address: address.trim(), date_of_birth: dateOfBirth } } }); if (error) setError(error.message); else if (data.session) await navigate({ to: "/dashboard" }); else setMessage(t.created); setLoading(false); }
  return <AuthShell title={t.title} description={t.desc}>
    <form onSubmit={handleRegister} className="space-y-4">{error && <div className="rounded-lg border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>}{message && <div className="rounded-lg border border-emerald-500/30 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-600">{message}</div>}
      <div className="grid gap-4 sm:grid-cols-2">
        <div className="space-y-2 sm:col-span-2"><Label htmlFor="name">{t.name}</Label><div className="relative"><User className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input id="name" autoComplete="name" placeholder={t.namePh} className="pl-9" value={name} onChange={(e) => setName(e.target.value)} required /></div></div>
        <div className="space-y-2"><Label htmlFor="email">{t.email}</Label><div className="relative"><Mail className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input id="email" type="email" autoComplete="email" placeholder={t.emailPh} className="pl-9" value={email} onChange={(e) => setEmail(e.target.value)} required /></div><p className="text-xs text-slate-500">{t.emailHint}</p></div>
        <div className="space-y-2"><Label htmlFor="phone">{t.phone}</Label><div className="relative"><Phone className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input id="phone" type="tel" autoComplete="tel" placeholder={t.phonePh} className="pl-9" value={phone} onChange={(e) => setPhone(e.target.value)} required /></div></div>
        <div className="space-y-2"><Label htmlFor="country">{t.country}</Label><div className="relative"><Globe2 className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><select id="country" value={country} onChange={(e) => setCountry(e.target.value)} required aria-label={t.country} className="h-10 w-full rounded-md border border-input bg-background pl-9 pr-3 text-sm"><option value="">{t.countryPh}</option>{countryOptions.map((item) => <option key={item.code} value={item.code}>{item.flag} {item.name}</option>)}</select></div></div>
        <div className="space-y-2"><Label htmlFor="dateOfBirth">{t.dob}</Label><div className="relative"><CalendarDays className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input id="dateOfBirth" type="date" max={maxBirthDate} autoComplete="bday" aria-label={t.dob} className="pl-9" value={dateOfBirth} onChange={(e) => setDateOfBirth(e.target.value)} required /></div><p className="text-xs text-slate-500">{t.dobHint}</p></div>
        <div className="space-y-2 sm:col-span-2"><Label htmlFor="address">{t.address}</Label><div className="relative"><MapPin className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input id="address" autoComplete="street-address" placeholder={t.addressPh} className="pl-9" value={address} onChange={(e) => setAddress(e.target.value)} required /></div></div>
        <div className="space-y-2 sm:col-span-2"><Label htmlFor="password">{t.password}</Label><div className="relative"><Lock className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input id="password" type={show ? "text" : "password"} autoComplete="new-password" placeholder={t.passwordPh} className="pl-9 pr-10" minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} required /><button type="button" onClick={() => setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground" aria-label={show ? t.hide : t.show}>{show ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></div></div>
      </div>
      <label className="flex items-start gap-3 rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm"><input type="checkbox" checked={accepted} onChange={(e) => setAccepted(e.target.checked)} className="mt-0.5 h-4 w-4 rounded border-slate-300" required aria-label={t.terms} /><span>{t.terms} <strong>{t.age}</strong>.</span></label>
      <Button type="submit" className="h-11 w-full" disabled={loading}>{loading ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />{t.loading}</> : t.create}</Button>
    </form><p className="mt-7 text-center text-sm text-muted-foreground">{t.already} <Link to="/login" className="font-semibold text-primary hover:underline">{t.login}</Link></p>
  </AuthShell>;
}
