import { useEffect, useState } from "react";
import { ClipboardList, Loader2, ShieldCheck } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useLanguage } from "@/lib/i18n";

type Audit = { id:string; actor_user_id:string; target_user_id:string|null; action:string; entity:string; entity_id:string|null; before_data:unknown; after_data:unknown; created_at:string };
const short=(id:string|null)=>id?id.slice(0,8)+"…":"—";
export function AdminAuditLogPanel({ userId }: { userId:string }) {
 const {language}=useLanguage(); const en=language==="en";
 const t=en?{title:"Administrative audit log",desc:"Recent privileged actions affecting users and financial data.",none:"No audit events yet.",loading:"Loading audit history…",actor:"Actor",target:"Target",action:"Action",date:"Date",before:"Before",after:"After",empty:"—"}:{title:"Registro de auditoría",desc:"Acciones administrativas recientes que afectan a usuarios y datos financieros.",none:"Aún no hay eventos de auditoría.",loading:"Cargando historial de auditoría…",actor:"Actor",target:"Objetivo",action:"Acción",date:"Fecha",before:"Antes",after:"Después",empty:"—"};
 const [allowed,setAllowed]=useState(false); const [loading,setLoading]=useState(true); const [items,setItems]=useState<Audit[]>([]); const [error,setError]=useState("");
 useEffect(()=>{let active=true;(async()=>{const db=supabase as any;const {data:ok,error:roleError}=await db.rpc("has_role",{_user_id:userId,_role:"admin"});if(!active)return;if(roleError||ok!==true){setLoading(false);return;}setAllowed(true);const {data,error:e}=await db.from("admin_audit_log").select("id,actor_user_id,target_user_id,action,entity,entity_id,before_data,after_data,created_at").order("created_at",{ascending:false}).limit(50);if(active){if(e)setError(e.message);else setItems((data??[]) as Audit[]);setLoading(false);}})();return()=>{active=false}},[userId]);
 if(loading)return <Card><CardContent className="p-6"><Loader2 className="h-5 w-5 animate-spin"/></CardContent></Card>; if(!allowed)return null;
 return <Card id="auditoria-admin" className="border-slate-200 shadow-sm"><CardHeader><div className="flex items-start gap-3"><div className="rounded-xl bg-slate-900 p-2 text-white"><ClipboardList className="h-5 w-5"/></div><div><CardTitle>{t.title}</CardTitle><CardDescription>{t.desc}</CardDescription></div></div></CardHeader><CardContent>{error?<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>:items.length===0?<div className="rounded-xl border border-dashed p-6 text-center text-sm text-slate-500">{t.none}</div>:<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="p-3">{t.action}</th><th className="p-3">{t.actor}</th><th className="p-3">{t.target}</th><th className="p-3">{t.date}</th><th className="p-3">{t.before}</th><th className="p-3">{t.after}</th></tr></thead><tbody>{items.map(i=><tr key={i.id} className="border-b last:border-0"><td className="p-3"><div className="font-medium">{i.action}</div><div className="text-xs text-slate-400">{i.entity} · {short(i.entity_id)}</div></td><td className="p-3 font-mono text-xs">{short(i.actor_user_id)}</td><td className="p-3 font-mono text-xs">{short(i.target_user_id)}</td><td className="p-3 whitespace-nowrap">{new Intl.DateTimeFormat(en?"en-US":"es-ES",{dateStyle:"medium",timeStyle:"short"}).format(new Date(i.created_at))}</td><td className="max-w-[220px] p-3 text-xs text-slate-500"><pre className="max-h-20 overflow-auto whitespace-pre-wrap">{i.before_data?JSON.stringify(i.before_data):t.empty}</pre></td><td className="max-w-[220px] p-3 text-xs text-slate-500"><pre className="max-h-20 overflow-auto whitespace-pre-wrap">{i.after_data?JSON.stringify(i.after_data):t.empty}</pre></td></tr>)}</tbody></table></div>}<div className="mt-4 flex items-center gap-2 text-xs text-slate-500"><ShieldCheck className="h-4 w-4"/>{en?"Only administrators can read this history; clients cannot write audit entries.":"Solo los administradores pueden leer este historial; los clientes no pueden escribir entradas de auditoría."}</div></CardContent></Card>;
}
