import { useEffect, useState } from "react";
import { LifeBuoy, Loader2, RefreshCw, Send } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useLanguage } from "@/lib/i18n";

type Message = { id: string; user_id: string; role: "user" | "assistant"; content: string; created_at: string };
type User = { user_id: string; full_name: string | null; email: string };
export function AdminSupportPanel({ userId }: { userId: string }) {
  const { language } = useLanguage(); const en = language === "en";
  const t = en ? { title:"Support center", desc:"Review recent NOVA AI conversations and send a support reply from the admin console.", user:"Select user", load:"Load conversation", reply:"Reply", sending:"Sending…", placeholder:"Write a support reply…", empty:"No messages found.", error:"Unable to load support data." } : { title:"Centro de soporte", desc:"Revisa conversaciones recientes de NOVA AI y envía respuestas de soporte desde el panel de administración.", user:"Seleccionar usuario", load:"Cargar conversación", reply:"Responder", sending:"Enviando…", placeholder:"Escribe una respuesta de soporte…", empty:"No hay mensajes.", error:"No se pudieron cargar los datos de soporte." };
  const [allowed,setAllowed]=useState(false),[users,setUsers]=useState<User[]>([]),[target,setTarget]=useState(""),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(""),[checking,setChecking]=useState(true),[loading,setLoading]=useState(false),[sending,setSending]=useState(false),[error,setError]=useState("");
  useEffect(()=>{let active=true;void (async()=>{const db=supabase as any;const {data,error:e}=await db.rpc("has_role",{_user_id:userId,_role:"admin"});if(!active)return;const ok=!e&&data===true;setAllowed(ok);if(ok){const {data:list,error:listError}=await db.rpc("admin_list_users");if(listError)setError(t.error);else setUsers((list??[])as User[]);}setChecking(false);})();return()=>{active=false}},[userId,t.error]);
  async function load(){if(!target.trim())return;setLoading(true);setError("");const db=supabase as any;const {data,error:e}=await db.rpc("admin_get_chat_messages",{target_user_id:target.trim()});if(e)setError(e.message||t.error);else setMessages((data??[])as Message[]);setLoading(false);}
  async function send(){if(!target.trim()||!text.trim())return;setSending(true);setError("");const db=supabase as any;const {error:e}=await db.rpc("admin_send_support_message",{target_user_id:target.trim(),message_content:text.trim()});if(e)setError(e.message||t.error);else{setText("");await load();}setSending(false);}
  if(checking)return <Card><CardContent className="p-6"><Loader2 className="h-5 w-5 animate-spin"/></CardContent></Card>;if(!allowed)return null;
  return <Card id="centro-soporte" className="shadow-sm"><CardHeader><div className="flex items-start gap-3"><div className="rounded-xl bg-slate-900 p-2 text-white"><LifeBuoy className="h-5 w-5"/></div><div><CardTitle>{t.title}</CardTitle><CardDescription>{t.desc}</CardDescription></div></div></CardHeader><CardContent className="space-y-4"><div className="flex flex-col gap-2 sm:flex-row"><select value={target} onChange={e=>{setTarget(e.target.value);setMessages([])}} className="h-10 min-w-0 flex-1 rounded-md border border-input bg-background px-3 text-sm"><option value="">{t.user}</option>{users.map(user=><option key={user.user_id} value={user.user_id}>{user.full_name||user.email} · {user.email}</option>)}</select><Button className="w-full sm:w-auto" onClick={()=>void load()} disabled={loading||!target}>{loading?<Loader2 className="animate-spin"/>:<RefreshCw/>}{t.load}</Button></div>{error&&<p className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="max-h-80 space-y-2 overflow-auto rounded-xl border bg-slate-50 p-3">{loading?<div className="flex justify-center p-6"><Loader2 className="h-5 w-5 animate-spin"/></div>:messages.length?messages.map(m=><div key={m.id} className={`min-w-0 rounded-xl p-3 text-sm ${m.role==="user"?"bg-white":"bg-slate-900 text-white"}`}><div className="mb-1 text-xs opacity-60">{m.role} · {new Date(m.created_at).toLocaleString(en?"en-US":"es-ES")}</div><p className="whitespace-pre-wrap break-words">{m.content}</p></div>):<p className="p-4 text-sm text-slate-500">{t.empty}</p>}</div><div className="flex flex-col gap-2 sm:flex-row"><Input value={text} onChange={e=>setText(e.target.value)} placeholder={t.placeholder} maxLength={12000} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send();}}}/><Button className="w-full sm:w-auto" onClick={()=>void send()} disabled={sending||!text.trim()||!target}>{sending?<Loader2 className="animate-spin"/>:<Send/>}{sending?t.sending:t.reply}</Button></div></CardContent></Card>;
}
