import { useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, Loader2, ShieldAlert } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useLanguage } from "@/lib/i18n";

type User={user_id:string;full_name:string|null;email:string;role:string}; type Risk={user_id:string;max_position_usd:number;max_daily_loss_usd:number;max_open_positions:number;max_drawdown_pct:number;kill_switch:boolean};
export function AdminRiskControlsPanel({userId}:{userId:string}){
 const {language}=useLanguage();const en=language==="en";const t=en?{title:"Risk controls",desc:"Review and adjust server-enforced risk limits for each user. LIVE execution remains disabled.",select:"Select user",position:"Max position (USD)",daily:"Max daily loss (USD)",open:"Max open positions",drawdown:"Max drawdown (%)",kill:"Kill switch",on:"ON",off:"OFF",save:"Save limits",saving:"Saving…",saved:"Risk limits saved.",noUser:"Choose a user to manage risk limits.",loading:"Loading…",safety:"Changes are processed by an admin-only server function and recorded in the audit log."}:{title:"Controles de riesgo",desc:"Revisa y ajusta los límites de riesgo aplicados en servidor a cada usuario. La ejecución LIVE sigue desactivada.",select:"Seleccionar usuario",position:"Posición máxima (USD)",daily:"Pérdida diaria máxima (USD)",open:"Máximo de posiciones abiertas",drawdown:"Drawdown máximo (%)",kill:"Kill switch",on:"ACTIVO",off:"INACTIVO",save:"Guardar límites",saving:"Guardando…",saved:"Límites de riesgo guardados.",noUser:"Selecciona un usuario para gestionar sus límites.",loading:"Cargando…",safety:"Los cambios se procesan mediante una función exclusiva para administradores y quedan registrados en auditoría."};
 const [allowed,setAllowed]=useState(false),[users,setUsers]=useState<User[]>([]),[selected,setSelected]=useState(""),[risk,setRisk]=useState<Risk|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 useEffect(()=>{let active=true;(async()=>{const db=supabase as any;const {data,error:roleError}=await db.rpc("has_role",{_user_id:userId,_role:"admin"});if(!active)return;const ok=!roleError&&data===true;setAllowed(ok);if(!ok){setLoading(false);return;}const {data:list,error:e}=await db.rpc("admin_list_users");if(active){if(e)setError(e.message);else setUsers((list??[])as User[]);setLoading(false);}})();return()=>{active=false}},[userId]);
 async function loadRisk(target:string){setSelected(target);setRisk(null);setMessage("");setError("");if(!target)return;const db=supabase as any;const {data,error:e}=await db.from("risk_controls").select("user_id,max_position_usd,max_daily_loss_usd,max_open_positions,max_drawdown_pct,kill_switch").eq("user_id",target).maybeSingle();if(e){setError(e.message);return;}setRisk((data as Risk)||{user_id:target,max_position_usd:250,max_daily_loss_usd:100,max_open_positions:3,max_drawdown_pct:10,kill_switch:false});}
 async function save(){if(!risk)return;setSaving(true);setMessage("");setError("");const db=supabase as any;const {error:e}=await db.rpc("admin_upsert_risk_controls",{target_user_id:risk.user_id,new_max_position_usd:Number(risk.max_position_usd),new_max_daily_loss_usd:Number(risk.max_daily_loss_usd),new_max_open_positions:Number(risk.max_open_positions),new_max_drawdown_pct:Number(risk.max_drawdown_pct),new_kill_switch:risk.kill_switch});setSaving(false);if(e){setError(e.message);return;}setMessage(t.saved);}
 if(loading)return <Card><CardContent className="p-6"><Loader2 className="h-5 w-5 animate-spin"/></CardContent></Card>;if(!allowed)return null;
 return <Card id="controles-riesgo" className="border-amber-200 shadow-sm"><CardHeader><div className="flex items-start gap-3"><div className="rounded-xl bg-amber-500 p-2 text-white"><ShieldAlert className="h-5 w-5"/></div><div><CardTitle>{t.title}</CardTitle><CardDescription>{t.desc}</CardDescription></div></div></CardHeader><CardContent className="space-y-5">{message&&<div className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700"><CheckCircle2 className="h-4 w-4"/>{message}</div>}{error&&<div className="flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertTriangle className="h-4 w-4"/>{error}</div>}<select className="h-10 w-full rounded-md border border-slate-300 bg-white px-3 text-sm" value={selected} onChange={e=>void loadRisk(e.target.value)}><option value="">{t.select}</option>{users.map(u=><option key={u.user_id} value={u.user_id}>{u.full_name||u.email} · {u.email}</option>)}</select>{!risk?<p className="text-sm text-slate-500">{t.noUser}</p>:<div className="grid gap-4 md:grid-cols-2">{([["max_position_usd",t.position],["max_daily_loss_usd",t.daily],["max_open_positions",t.open],["max_drawdown_pct",t.drawdown]] as const).map(([key,label])=><label key={key} className="space-y-1 text-sm font-medium">{label}<Input type="number" min="0.01" step="0.01" value={risk[key]} onChange={e=>setRisk({...risk,[key]:Number(e.target.value)})}/></label>)}<div className="flex items-center justify-between rounded-xl border bg-slate-50 p-3 md:col-span-2"><div><p className="font-medium">{t.kill}</p><p className="text-xs text-slate-500">{risk.kill_switch?t.on:t.off}</p></div><Button type="button" variant={risk.kill_switch?"destructive":"outline"} onClick={()=>setRisk({...risk,kill_switch:!risk.kill_switch})}>{risk.kill_switch?t.on:t.off}</Button></div><Button className="md:col-span-2" onClick={()=>void save()} disabled={saving}>{saving?<Loader2 className="animate-spin"/>:null}{saving?t.saving:t.save}</Button></div>}<p className="text-xs text-slate-500">{t.safety}</p></CardContent></Card>;
}
