import { useEffect, useState } from "react";
import { CheckCircle2, Clock3, Loader2, ShieldCheck, XCircle } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useLanguage } from "@/lib/i18n";

type Request = { id: string; user_id: string; amount: number; method: string; status: string; created_at: string; destination?: string | null; };
const money = (v: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(v);

export function AdminFinancePanel({ userId }: { userId: string }) {
  const { language } = useLanguage(); const en = language === "en";
  const t = en ? { title: "Financial requests", desc: "Review pending deposits and withdrawals. Approved requests update the user's portfolio atomically.", dep: "Deposits", wit: "Withdrawals", none: "No pending requests.", approve: "Approve", reject: "Reject", processing: "Processing…", unauthorized: "Administrator access required.", error: "Action failed", success: "Request processed.", destination: "Destination", pending: "Pending", audit: "Every decision is recorded in the administrative audit log." } : { title: "Solicitudes financieras", desc: "Revisa depósitos y retiros pendientes. Las solicitudes aprobadas actualizan el portafolio del usuario de forma atómica.", dep: "Depósitos", wit: "Retiros", none: "No hay solicitudes pendientes.", approve: "Aprobar", reject: "Rechazar", processing: "Procesando…", unauthorized: "Se requiere acceso de administrador.", error: "La acción falló", success: "Solicitud procesada.", destination: "Destino", pending: "Pendiente", audit: "Cada decisión queda registrada en el registro de auditoría administrativa." };
  const [allowed, setAllowed] = useState(false); const [loading, setLoading] = useState(true); const [deposits, setDeposits] = useState<Request[]>([]); const [withdrawals, setWithdrawals] = useState<Request[]>([]); const [busy, setBusy] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function load() { const db = supabase as any; const { data, error: roleError } = await db.rpc("has_role", { _user_id: userId, _role: "admin" }); const ok = !roleError && data === true; setAllowed(ok); if (!ok) { setLoading(false); return; } const [{ data: d, error: de }, { data: w, error: we }] = await Promise.all([db.from("deposits").select("id,user_id,amount,method,status,created_at").order("created_at", { ascending: false }).limit(25), db.from("withdrawals").select("id,user_id,amount,method,status,created_at,destination").order("created_at", { ascending: false }).limit(25)]); if (de || we) setError((de || we)?.message || t.error); setDeposits((d ?? []) as Request[]); setWithdrawals((w ?? []) as Request[]); setLoading(false); }
  useEffect(() => { void load(); }, [userId]);
  async function review(kind: "deposit" | "withdrawal", id: string, decision: "approved" | "rejected") { setBusy(id); setMessage(""); setError(""); const db = supabase as any; const fn = kind === "deposit" ? "admin_review_deposit" : "admin_review_withdrawal"; const { error: actionError } = await db.rpc(fn, { request_id: id, decision }); setBusy(""); if (actionError) { setError(actionError.message); return; } setMessage(t.success); await load(); }
  const pending = (r: Request) => r.status.toLowerCase() === "pending";
  const date = (v: string) => new Intl.DateTimeFormat(en ? "en-US" : "es-ES", { dateStyle: "medium", timeStyle: "short" }).format(new Date(v));
  if (loading) return <Card><CardContent className="p-6"><Loader2 className="h-5 w-5 animate-spin" /></CardContent></Card>;
  if (!allowed) return null;
  const list = (items: Request[], kind: "deposit" | "withdrawal") => { const pendingItems = items.filter(pending); return pendingItems.length === 0 ? <div className="rounded-xl border border-dashed border-slate-300 p-6 text-center text-sm text-slate-500">{t.none}</div> : <div className="space-y-3">{pendingItems.map((item) => <div key={item.id} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{money(Number(item.amount))}</p><p className="text-xs text-slate-500">{item.method} · {date(item.created_at)}</p><p className="mt-1 break-all text-[11px] text-slate-400">User: {item.user_id}</p>{item.destination && <p className="mt-1 break-all text-xs text-slate-500">{t.destination}: {item.destination}</p>}</div><div className="flex flex-wrap gap-2"><Button size="sm" onClick={() => void review(kind, item.id, "approved")} disabled={!!busy}>{busy === item.id ? <Loader2 className="animate-spin" /> : <CheckCircle2 />}{t.approve}</Button><Button size="sm" variant="outline" onClick={() => void review(kind, item.id, "rejected")} disabled={!!busy}><XCircle />{t.reject}</Button></div></div></div>)}</div>; };
  return <Card id="solicitudes-financieras" className="border-slate-200 shadow-sm"><CardHeader><div className="flex items-start gap-3"><div className="rounded-xl bg-slate-900 p-2 text-white"><ShieldCheck className="h-5 w-5" /></div><div><CardTitle>{t.title}</CardTitle><CardDescription>{t.desc}</CardDescription></div></div></CardHeader><CardContent className="space-y-6">{message && <p className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}{error && <p className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<section><h3 className="mb-3 flex items-center gap-2 font-semibold"><Clock3 className="h-4 w-4" />{t.dep}</h3>{list(deposits, "deposit")}</section><section><h3 className="mb-3 flex items-center gap-2 font-semibold"><Clock3 className="h-4 w-4" />{t.wit}</h3>{list(withdrawals, "withdrawal")}</section><p className="text-xs text-slate-500">{t.audit}</p></CardContent></Card>;
}
