import { useEffect, useState } from "react";
import { AlertCircle, CheckCircle2, Save, ShieldCheck, Users } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { useLanguage } from "@/lib/i18n";

type UserProfile = { id: string; full_name: string; email: string };
type PortfolioValues = { balance: string; invested: string; total_deposited: string; today_pnl: string; total_pnl: string; performance_pct: string };
const emptyValues: PortfolioValues = { balance: "0", invested: "0", total_deposited: "0", today_pnl: "0", total_pnl: "0", performance_pct: "0" };
function numberValue(value: string) { const parsed = Number(value.replace(",", ".")); return Number.isFinite(parsed) ? parsed : NaN; }

export function AdminPortfolioControl({ userId }: { userId: string }) {
  const { language } = useLanguage(); const en = language === "en";
  const t = en ? { title:"Administration · Dashboard values", desc:"Visible only to administrators. You can modify the financial indicators for each user.", user:"User", select:"Select a user", unnamed:"No name", editing:"Editing:", balance:"Equity", balanceHint:"Total balance displayed", today:"Today's P&L", todayHint:"Today's result", total:"Total P&L", totalHint:"Accumulated gain", invested:"Invested capital", investedHint:"Capital currently invested", deposited:"Total deposited", depositedHint:"Deposited amount", performance:"Total performance (%)", performanceHint:"Percentage shown next to Equity", saving:"Saving...", save:"Save values", saved:"Dashboard values updated successfully.", numbers:"All values must be valid numbers.", negative:"Equity, invested capital and total deposited cannot be negative.", footer:"Changes are saved to the user's portfolio and reflected in their Equity, P&L and Invested capital cards." } : { title:"Administración · Valores del dashboard", desc:"Solo visible para administradores. Puedes modificar los indicadores financieros de cada usuario.", user:"Usuario", select:"Selecciona un usuario", unnamed:"Sin nombre", editing:"Editando:", balance:"Patrimonio", balanceHint:"Saldo total mostrado", today:"P&L de hoy", todayHint:"Resultado del día", total:"P&L total", totalHint:"Ganancia acumulada", invested:"Capital invertido", investedHint:"Capital actualmente invertido", deposited:"Total depositado", depositedHint:"Importe depositado", performance:"Rendimiento total (%)", performanceHint:"Porcentaje mostrado junto a Patrimonio", saving:"Guardando...", save:"Guardar valores", saved:"Valores del dashboard actualizados correctamente.", numbers:"Todos los valores deben ser números válidos.", negative:"Patrimonio, capital invertido y total depositado no pueden ser negativos.", footer:"Los cambios se guardan en el portafolio del usuario y se reflejan en sus tarjetas de Patrimonio, P&L y Capital invertido." };
  const [isAdmin, setIsAdmin] = useState(false); const [checking, setChecking] = useState(true); const [users, setUsers] = useState<UserProfile[]>([]); const [selectedUserId, setSelectedUserId] = useState(""); const [values, setValues] = useState<PortfolioValues>(emptyValues); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; async function load() { const db = supabase as any; const { data, error: roleError } = await db.rpc("has_role", { _user_id: userId, _role: "admin" }); if (!active) return; const allowed = !roleError && data === true; setIsAdmin(allowed); setChecking(false); if (!allowed) return; const { data: profiles, error: profilesError } = await db.rpc("admin_list_users"); if (profilesError) { setError(profilesError.message); return; } const list = ((profiles ?? []) as Array<{ user_id: string; full_name: string | null; email: string }>).map((user) => ({ id: user.user_id, full_name: user.full_name ?? "", email: user.email })); setUsers(list); if (list[0]) setSelectedUserId(list[0].id); } void load(); return () => { active = false; }; }, [userId]);
  useEffect(() => { if (!isAdmin || !selectedUserId) return; let active = true; async function loadPortfolio() { setError(null); const db = supabase as any; const { data, error: portfolioError } = await db.from("portfolio").select("balance,invested,total_deposited,today_pnl,total_pnl,performance_pct").eq("user_id", selectedUserId).maybeSingle(); if (!active) return; if (portfolioError) { setError(portfolioError.message); return; } setValues(data ? { balance:String(data.balance??0), invested:String(data.invested??0), total_deposited:String(data.total_deposited??0), today_pnl:String(data.today_pnl??0), total_pnl:String(data.total_pnl??0), performance_pct:String(data.performance_pct??0) } : emptyValues); } void loadPortfolio(); return () => { active = false; }; }, [isAdmin, selectedUserId]);
  if (checking || !isAdmin) return null;
  async function saveValues() { setMessage(null); setError(null); const parsed = Object.fromEntries(Object.entries(values).map(([key, value]) => [key, numberValue(value)])) as Record<keyof PortfolioValues, number>; if (Object.values(parsed).some((value) => !Number.isFinite(value))) { setError(t.numbers); return; } if (["balance", "invested", "total_deposited"].some((key) => parsed[key as keyof PortfolioValues] < 0)) { setError(t.negative); return; } setSaving(true); const db = supabase as any; const { error: saveError } = await db.rpc("admin_update_portfolio", { target_user_id: selectedUserId, new_balance: parsed.balance, new_invested: parsed.invested, new_total_deposited: parsed.total_deposited, new_today_pnl: parsed.today_pnl, new_total_pnl: parsed.total_pnl, new_performance_pct: parsed.performance_pct }); setSaving(false); if (saveError) setError(saveError.message); else setMessage(t.saved); }
  const selectedUser = users.find((user) => user.id === selectedUserId); const setValue = (key: keyof PortfolioValues, value: string) => setValues((current) => ({ ...current, [key]: value }));
  const fields: [keyof PortfolioValues, string, string][] = [["balance",t.balance,t.balanceHint],["today_pnl",t.today,t.todayHint],["total_pnl",t.total,t.totalHint],["invested",t.invested,t.investedHint],["total_deposited",t.deposited,t.depositedHint],["performance_pct",t.performance,t.performanceHint]];
  return <Card id="administracion" className="border-blue-200 bg-blue-50/30 shadow-sm"><CardHeader><div className="flex items-center gap-3"><div className="rounded-xl bg-blue-600 p-2 text-white"><ShieldCheck className="h-5 w-5" /></div><div><CardTitle>{t.title}</CardTitle><CardDescription>{t.desc}</CardDescription></div></div></CardHeader><CardContent className="space-y-5">{message && <div className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700"><CheckCircle2 className="h-4 w-4" />{message}</div>}{error && <div className="flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><AlertCircle className="h-4 w-4" />{error}</div>}<div className="space-y-2"><label className="text-sm font-medium" htmlFor="admin-user">{t.user}</label><div className="relative"><Users className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><select id="admin-user" aria-label={t.user} value={selectedUserId} onChange={(event) => { setSelectedUserId(event.target.value); setMessage(null); }} className="h-10 w-full rounded-md border border-input bg-background pl-9 pr-3 text-sm"><option value="">{t.select}</option>{users.map((user) => <option key={user.id} value={user.id}>{user.full_name || t.unnamed} · {user.email}</option>)}</select></div>{selectedUser && <p className="text-xs text-slate-500">{t.editing} {selectedUser.email}</p>}</div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{fields.map(([key,label,hint])=><div key={key} className="space-y-2"><label className="text-sm font-medium" htmlFor={`admin-${key}`}>{label}</label><Input id={`admin-${key}`} inputMode="decimal" aria-label={label} value={values[key]} onChange={(event) => setValue(key,event.target.value)} /><p className="text-xs text-slate-500">{hint}</p></div>)}</div><Button onClick={saveValues} disabled={!selectedUserId || saving}><Save />{saving ? t.saving : t.save}</Button><p className="text-xs text-slate-500">{t.footer}</p></CardContent></Card>;
}
