import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useLanguage } from "@/lib/i18n";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type Snapshot = { equity: number; today_pnl: number; total_pnl: number; created_at: string };
type RangeKey = "7D" | "30D" | "90D" | "1Y";

const ranges: { key: RangeKey; days: number }[] = [
  { key: "7D", days: 7 }, { key: "30D", days: 30 }, { key: "90D", days: 90 }, { key: "1Y", days: 365 },
];

export function DemoPerformanceHistory({ userId }: { userId: string }) {
  const { language } = useLanguage();
  const en = language === "en";
  const [range, setRange] = useState<RangeKey>("7D");
  const [snapshots, setSnapshots] = useState<Snapshot[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    let active = true;
    async function load() {
      setLoading(true); setError("");
      const days = ranges.find((item) => item.key === range)?.days ?? 7;
      const since = new Date(Date.now() - days * 86400000).toISOString();
      const { data, error: queryError } = await supabase
        .from("demo_equity_snapshots")
        .select("equity,today_pnl,total_pnl,created_at")
        .eq("user_id", userId)
        .gte("created_at", since)
        .order("created_at", { ascending: true })
        .limit(500);
      if (!active) return;
      if (queryError) setError(queryError.message);
      setSnapshots((data ?? []) as Snapshot[]);
      setLoading(false);
    }
    void load();
    return () => { active = false; };
  }, [userId, range]);

  const chartData = useMemo(() => snapshots.map((item) => ({
    time: new Date(item.created_at).toLocaleDateString(en ? "en-US" : "es-ES", { month: "short", day: "numeric" }),
    equity: Number(item.equity),
    pnl: Number(item.total_pnl),
  })), [snapshots, en]);

  const latest = snapshots[snapshots.length - 1];
  const first = snapshots[0];
  const change = latest && first ? Number(latest.equity) - Number(first.equity) : 0;

  return <Card className="border-slate-200 shadow-sm">
    <CardHeader className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
      <div><CardTitle>{en ? "DEMO performance history" : "Histórico de rendimiento DEMO"}</CardTitle><p className="mt-1 text-sm text-slate-500">{en ? "Historical equity generated by DEMO execution cycles." : "Patrimonio histórico generado por los ciclos de ejecución DEMO."}</p></div>
      <div className="flex rounded-lg border bg-white p-1">{ranges.map((item) => <Button key={item.key} type="button" size="sm" variant={range === item.key ? "default" : "ghost"} onClick={() => setRange(item.key)}>{item.key}</Button>)}</div>
    </CardHeader>
    <CardContent>
      {loading ? <div className="h-[280px] flex items-center justify-center text-sm text-slate-500">{en ? "Loading DEMO history..." : "Cargando histórico DEMO..."}</div>
        : error ? <div className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>
        : !chartData.length ? <div className="h-[280px] flex items-center justify-center rounded-lg border border-dashed text-sm text-slate-500">{en ? "Run a DEMO cycle to start building historical data." : "Ejecuta un ciclo DEMO para comenzar a generar datos históricos."}</div>
        : <>
          <div className="mb-4 flex flex-wrap gap-5 text-sm"><span><span className="text-slate-500">{en ? "Current equity" : "Patrimonio actual"}: </span><strong>${Number(latest.equity).toFixed(2)}</strong></span><span><span className="text-slate-500">{en ? "Range change" : "Cambio del período"}: </span><strong className={change >= 0 ? "text-emerald-600" : "text-red-600"}>{change >= 0 ? "+" : ""}${change.toFixed(2)}</strong></span><span><span className="text-slate-500">{en ? "Snapshots" : "Registros"}: </span><strong>{snapshots.length}</strong></span></div>
          <div className="h-[280px] w-full"><ResponsiveContainer width="100%" height="100%"><LineChart data={chartData} margin={{ top: 8, right: 8, left: 8, bottom: 8 }}><XAxis dataKey="time" tick={{ fontSize: 11 }} minTickGap={24} /><YAxis tick={{ fontSize: 11 }} width={70} tickFormatter={(value) => `$${Number(value).toLocaleString()}`} /><Tooltip formatter={(value, name) => [name === "equity" ? `$${Number(value).toFixed(2)}` : `$${Number(value).toFixed(2)}`, name === "equity" ? (en ? "Equity" : "Patrimonio") : "P&L"]} /><Line type="monotone" dataKey="equity" dot={false} strokeWidth={2} name="equity" /></LineChart></ResponsiveContainer></div>
        </>}
    </CardContent>
  </Card>;
}
