import { useEffect, useRef, useState } from "react";
import { Bot, Loader2, MessageCircle, Send, Sparkles, X } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useLanguage } from "@/lib/i18n";

type Msg={id?:string;role:"user"|"assistant";content:string};
export function NovaAIChat({userId}:{userId?:string}){
 const {language}=useLanguage(); const en=language==="en"; const [open,setOpen]=useState(false),[msgs,setMsgs]=useState<Msg[]>([]),[text,setText]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""); const end=useRef<HTMLDivElement>(null);
 const welcome=en?"Hi! I’m NOVA AI. Ask me about your DEMO portfolio, risk, performance or trading concepts.":"¡Hola! Soy NOVA AI. Pregúntame sobre tu portafolio DEMO, riesgo, rendimiento o conceptos de trading.";
 useEffect(()=>{end.current?.scrollIntoView({behavior:"smooth"})},[msgs,busy]);
 useEffect(()=>{if(!open||!userId)return;let live=true;(async()=>{const {data}=await supabase.from("ai_chat_messages").select("id,role,content").eq("user_id",userId).order("created_at",{ascending:true}).limit(100);if(live&&data)setMsgs(data as Msg[])})();return()=>{live=false}},[open,userId]);
 async function send(value=text){const content=value.trim();if(!content||busy||!userId)return;setText("");setError("");const next=[...msgs,{role:"user" as const,content}];setMsgs(next);setBusy(true);await supabase.from("ai_chat_messages").insert({user_id:userId,role:"user",content});try{const {data,error:e}=await supabase.functions.invoke("nova-ai-chat",{body:{messages:next.map(m=>({role:m.role,content:m.content}))}});if(e)throw e;if(!data?.content)throw new Error(en?"AI provider unavailable":"Proveedor de IA no disponible");setMsgs(m=>[...m,{role:"assistant",content:data.content}]);await supabase.from("ai_chat_messages").insert({user_id:userId,role:"assistant",content:data.content})}catch(e){setError(e instanceof Error?e.message:(en?"Unable to answer right now.":"No puedo responder ahora."))}finally{setBusy(false)}}
 if(!userId)return null; return <><Button onClick={()=>setOpen(v=>!v)} className="fixed bottom-5 right-4 z-50 h-14 w-14 rounded-full bg-blue-600 p-0 shadow-xl hover:bg-blue-700 sm:right-6" aria-label="NOVA AI"><MessageCircle className="h-6 w-6"/></Button>{open&&<div className="fixed bottom-24 right-4 z-50 flex h-[min(680px,calc(100vh-7rem))] w-[min(420px,calc(100vw-2rem))] flex-col overflow-hidden rounded-2xl border bg-white shadow-2xl sm:right-6"><header className="flex items-center justify-between bg-slate-950 px-4 py-3 text-white"><div className="flex items-center gap-3"><div className="rounded-xl bg-blue-600 p-2"><Bot className="h-5 w-5"/></div><div><b>NOVA AI</b><p className="text-[11px] text-slate-400">{en?"AI trading assistant":"Asistente de trading con IA"}</p></div></div><Button variant="ghost" size="icon" className="text-white" onClick={()=>setOpen(false)}><X/></Button></header><main className="flex-1 space-y-3 overflow-y-auto bg-slate-50 p-4">{msgs.length===0&&<div className="rounded-2xl border bg-white p-4"><div className="mb-2 flex gap-2 text-sm font-semibold"><Sparkles className="h-4 w-4 text-blue-600"/>NOVA AI</div><p className="text-sm leading-6 text-slate-600">{welcome}</p><div className="mt-4 space-y-2">{(en?["Explain my portfolio","How does drawdown work?","What is a safe position size?"]:["Explícame mi portafolio","¿Cómo funciona el drawdown?","¿Cuál es un tamaño de posición prudente?"]).map(s=><button key={s} onClick={()=>void send(s)} className="block w-full rounded-xl border bg-slate-50 px-3 py-2 text-left text-xs hover:bg-blue-50">{s}</button>)}</div></div>}{msgs.map((m,i)=><div key={m.id||i} className={`flex ${m.role==="user"?"justify-end":"justify-start"}`}><div className={`max-w-[85%] whitespace-pre-wrap rounded-2xl px-3 py-2.5 text-sm ${m.role==="user"?"rounded-br-md bg-blue-600 text-white":"rounded-bl-md border bg-white text-slate-700 shadow-sm"}`}>{m.content}</div></div>)}{busy&&<div className="flex gap-2 text-xs text-slate-500"><Loader2 className="h-4 w-4 animate-spin"/>{en?"NOVA AI is thinking…":"NOVA AI está pensando…"}</div>}{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</div>}<div ref={end}/></main><footer className="border-t bg-white p-3"><p className="mb-2 text-[10px] text-slate-400">{en?"DEMO only · no real trades are executed.":"Solo DEMO · no se ejecutan operaciones reales."}</p><form className="flex gap-2" onSubmit={e=>{e.preventDefault();void send()}}><Input value={text} onChange={e=>setText(e.target.value)} placeholder={en?"Ask NOVA AI…":"Pregunta a NOVA AI…"} maxLength={4000} disabled={busy}/><Button type="submit" disabled={busy||!text.trim()}><Send className="h-4 w-4"/></Button></form></footer></div>}</>;
}
