import { useEffect, useState } from "react";
import { Save, SlidersHorizontal } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";

type Settings = { language: string; currency: string; theme: string; email_notifications: boolean; push_notifications: boolean; risk_alerts: boolean; two_factor_enabled: boolean };
const defaults: Settings = { language: "es", currency: "USD", theme: "dark", email_notifications: true, push_notifications: false, risk_alerts: true, two_factor_enabled: false };
export function PreferencesPagePanel({ userId }: { userId: string }) {
  const [settings, setSettings] = useState(defaults); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { let active = true; (async () => { const { data } = await supabase.from("settings").select("language,currency,theme,email_notifications,push_notifications,risk_alerts,two_factor_enabled").eq("user_id", userId).maybeSingle(); if (active && data) setSettings(data as Settings); })(); return () => { active = false; }; }, [userId]);
  async function save() { setSaving(true); setMessage(""); setError(""); const { error: e } = await supabase.from("settings").upsert({ user_id: userId, ...settings }); setSaving(false); if (e) setError(e.message); else setMessage("Preferencias guardadas correctamente."); }
  return <Card className="border-slate-200 shadow-sm"><CardHeader><div className="flex items-center gap-3"><div className="rounded-xl bg-blue-50 p-2 text-blue-600"><SlidersHorizontal className="h-5 w-5" /></div><div><CardTitle>Preferencias</CardTitle><CardDescription>Configura la experiencia de Trade Nova AI. Esta página no contiene datos personales ni cambio de contraseña.</CardDescription></div></div></CardHeader><CardContent className="space-y-6">{message && <p className="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</p>}{error && <p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<div className="grid gap-5 sm:grid-cols-3"><div className="space-y-2"><label className="text-sm font-medium">Idioma</label><select value={settings.language} onChange={(e) => setSettings({ ...settings, language: e.target.value })} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="es">Español</option><option value="pt-BR">Português (Brasil)</option><option value="en">English</option></select></div><div className="space-y-2"><label className="text-sm font-medium">Moneda</label><select value={settings.currency} onChange={(e) => setSettings({ ...settings, currency: e.target.value })} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="USD">USD — Dólar</option><option value="BRL">BRL — Real</option><option value="EUR">EUR — Euro</option></select></div><div className="space-y-2"><label className="text-sm font-medium">Tema</label><select value={settings.theme} onChange={(e) => setSettings({ ...settings, theme: e.target.value })} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="dark">Oscuro</option><option value="light">Claro</option><option value="system">Sistema</option></select></div></div><div className="divide-y rounded-xl border">{[["email_notifications", "Notificaciones por email", "Actualizaciones importantes de tu cuenta."], ["push_notifications", "Notificaciones push", "Avisos en tiempo real cuando estén disponibles."], ["risk_alerts", "Alertas de riesgo", "Cambios relevantes de riesgo y actividad."]].map(([key, title, description]) => <div key={key} className="flex items-center justify-between gap-4 p-4"><div><p className="text-sm font-medium">{title}</p><p className="text-xs text-slate-500">{description}</p></div><Switch checked={settings[key as keyof Settings] as boolean} onCheckedChange={(checked) => setSettings({ ...settings, [key]: checked })} /></div>)}</div><Button onClick={save} disabled={saving}><Save />{saving ? "Guardando..." : "Guardar preferencias"}</Button></CardContent></Card>;
}
