import { useState } from "react";
import { KeyRound, LockKeyhole, ShieldCheck } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
export function SecurityPagePanel({ userId: _userId }: { userId: string }) {
  const [newPassword, setNewPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function changePassword() { setMessage(""); setError(""); if (newPassword.length < 8) { setError("La nueva contraseña debe tener al menos 8 caracteres."); return; } if (newPassword !== confirm) { setError("Las contraseñas no coinciden."); return; } setSaving(true); const { error: e } = await supabase.auth.updateUser({ password: newPassword }); setSaving(false); if (e) setError(e.message); else { setNewPassword(""); setConfirm(""); setMessage("Contraseña actualizada correctamente."); } }
  return <div className="space-y-6">{message && <p className="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</p>}{error && <p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<Card className="border-slate-200 shadow-sm"><CardHeader><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-50 p-2 text-emerald-600"><ShieldCheck className="h-5 w-5" /></div><div><CardTitle>Seguridad de la cuenta</CardTitle><CardDescription>Protege el acceso a tu cuenta. Esta página está dedicada exclusivamente a seguridad.</CardDescription></div></div></CardHeader><CardContent className="space-y-6"><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl border p-4"><div className="flex items-center gap-3"><LockKeyhole className="h-5 w-5 text-emerald-600" /><div><p className="font-medium">Contraseña</p><p className="text-xs text-slate-500">Gestionada de forma segura mediante Supabase Auth.</p></div></div></div><div className="rounded-xl border p-4"><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-slate-500" /><div><p className="font-medium">Autenticación de dos factores</p><p className="text-xs text-slate-500">Disponible para integración con MFA de Supabase.</p></div></div></div></div><div className="max-w-xl space-y-4 rounded-xl border p-5"><div className="flex items-center gap-2"><KeyRound className="h-4 w-4" /><p className="font-semibold">Cambiar contraseña</p></div><Input type="password" value={newPassword} onChange={(e) => setNewPassword(e.target.value)} placeholder="Nueva contraseña (mín. 8 caracteres)" autoComplete="new-password" /><Input type="password" value={confirm} onChange={(e) => setConfirm(e.target.value)} placeholder="Confirmar nueva contraseña" autoComplete="new-password" /><Button onClick={changePassword} disabled={saving}>{saving ? "Actualizando..." : "Actualizar contraseña"}</Button></div></CardContent></Card></div>;
}
