/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DashboardAdminRouteImport } from './routes/dashboard_.admin'
import { Route as DashboardFondosRouteImport } from './routes/dashboard_.fondos'
import { Route as DashboardNotificacionesRouteImport } from './routes/dashboard_.notificaciones'
import { Route as DashboardOperacionesRouteImport } from './routes/dashboard_.operaciones'
import { Route as DashboardPerfilRouteImport } from './routes/dashboard_.perfil'
import { Route as DashboardPortafolioRouteImport } from './routes/dashboard_.portafolio'
import { Route as DashboardPreferenciasRouteImport } from './routes/dashboard_.preferencias'
import { Route as DashboardRobotRouteImport } from './routes/dashboard_.robot'
import { Route as DashboardSeguridadRouteImport } from './routes/dashboard_.seguridad'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard_/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFondosRoute = DashboardFondosRouteImport.update({
  id: '/dashboard_/fondos',
  path: '/dashboard/fondos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNotificacionesRoute = DashboardNotificacionesRouteImport.update({
  id: '/dashboard_/notificaciones',
  path: '/dashboard/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOperacionesRoute = DashboardOperacionesRouteImport.update({
  id: '/dashboard_/operaciones',
  path: '/dashboard/operaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPerfilRoute = DashboardPerfilRouteImport.update({
  id: '/dashboard_/perfil',
  path: '/dashboard/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPortafolioRoute = DashboardPortafolioRouteImport.update({
  id: '/dashboard_/portafolio',
  path: '/dashboard/portafolio',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPreferenciasRoute = DashboardPreferenciasRouteImport.update({
  id: '/dashboard_/preferencias',
  path: '/dashboard/preferencias',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRobotRoute = DashboardRobotRouteImport.update({
  id: '/dashboard_/robot',
  path: '/dashboard/robot',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSeguridadRoute = DashboardSeguridadRouteImport.update({
  id: '/dashboard_/seguridad',
  path: '/dashboard/seguridad',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/fondos': typeof DashboardFondosRoute
  '/dashboard/notificaciones': typeof DashboardNotificacionesRoute
  '/dashboard/operaciones': typeof DashboardOperacionesRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/portafolio': typeof DashboardPortafolioRoute
  '/dashboard/preferencias': typeof DashboardPreferenciasRoute
  '/dashboard/robot': typeof DashboardRobotRoute
  '/dashboard/seguridad': typeof DashboardSeguridadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/fondos': typeof DashboardFondosRoute
  '/dashboard/notificaciones': typeof DashboardNotificacionesRoute
  '/dashboard/operaciones': typeof DashboardOperacionesRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/portafolio': typeof DashboardPortafolioRoute
  '/dashboard/preferencias': typeof DashboardPreferenciasRoute
  '/dashboard/robot': typeof DashboardRobotRoute
  '/dashboard/seguridad': typeof DashboardSeguridadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard_/admin': typeof DashboardAdminRoute
  '/dashboard_/fondos': typeof DashboardFondosRoute
  '/dashboard_/notificaciones': typeof DashboardNotificacionesRoute
  '/dashboard_/operaciones': typeof DashboardOperacionesRoute
  '/dashboard_/perfil': typeof DashboardPerfilRoute
  '/dashboard_/portafolio': typeof DashboardPortafolioRoute
  '/dashboard_/preferencias': typeof DashboardPreferenciasRoute
  '/dashboard_/robot': typeof DashboardRobotRoute
  '/dashboard_/seguridad': typeof DashboardSeguridadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/admin'
    | '/dashboard/fondos'
    | '/dashboard/notificaciones'
    | '/dashboard/operaciones'
    | '/dashboard/perfil'
    | '/dashboard/portafolio'
    | '/dashboard/preferencias'
    | '/dashboard/robot'
    | '/dashboard/seguridad'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/admin'
    | '/dashboard/fondos'
    | '/dashboard/notificaciones'
    | '/dashboard/operaciones'
    | '/dashboard/perfil'
    | '/dashboard/portafolio'
    | '/dashboard/preferencias'
    | '/dashboard/robot'
    | '/dashboard/seguridad'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard_/admin'
    | '/dashboard_/fondos'
    | '/dashboard_/notificaciones'
    | '/dashboard_/operaciones'
    | '/dashboard_/perfil'
    | '/dashboard_/portafolio'
    | '/dashboard_/preferencias'
    | '/dashboard_/robot'
    | '/dashboard_/seguridad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardFondosRoute: typeof DashboardFondosRoute
  DashboardNotificacionesRoute: typeof DashboardNotificacionesRoute
  DashboardOperacionesRoute: typeof DashboardOperacionesRoute
  DashboardPerfilRoute: typeof DashboardPerfilRoute
  DashboardPortafolioRoute: typeof DashboardPortafolioRoute
  DashboardPreferenciasRoute: typeof DashboardPreferenciasRoute
  DashboardRobotRoute: typeof DashboardRobotRoute
  DashboardSeguridadRoute: typeof DashboardSeguridadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/admin': {
      id: '/dashboard_/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/fondos': {
      id: '/dashboard_/fondos'
      path: '/dashboard/fondos'
      fullPath: '/dashboard/fondos'
      preLoaderRoute: typeof DashboardFondosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/notificaciones': {
      id: '/dashboard_/notificaciones'
      path: '/dashboard/notificaciones'
      fullPath: '/dashboard/notificaciones'
      preLoaderRoute: typeof DashboardNotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/operaciones': {
      id: '/dashboard_/operaciones'
      path: '/dashboard/operaciones'
      fullPath: '/dashboard/operaciones'
      preLoaderRoute: typeof DashboardOperacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/perfil': {
      id: '/dashboard_/perfil'
      path: '/dashboard/perfil'
      fullPath: '/dashboard/perfil'
      preLoaderRoute: typeof DashboardPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/portafolio': {
      id: '/dashboard_/portafolio'
      path: '/dashboard/portafolio'
      fullPath: '/dashboard/portafolio'
      preLoaderRoute: typeof DashboardPortafolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/preferencias': {
      id: '/dashboard_/preferencias'
      path: '/dashboard/preferencias'
      fullPath: '/dashboard/preferencias'
      preLoaderRoute: typeof DashboardPreferenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/robot': {
      id: '/dashboard_/robot'
      path: '/dashboard/robot'
      fullPath: '/dashboard/robot'
      preLoaderRoute: typeof DashboardRobotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/seguridad': {
      id: '/dashboard_/seguridad'
      path: '/dashboard/seguridad'
      fullPath: '/dashboard/seguridad'
      preLoaderRoute: typeof DashboardSeguridadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardFondosRoute: DashboardFondosRoute,
  DashboardNotificacionesRoute: DashboardNotificacionesRoute,
  DashboardOperacionesRoute: DashboardOperacionesRoute,
  DashboardPerfilRoute: DashboardPerfilRoute,
  DashboardPortafolioRoute: DashboardPortafolioRoute,
  DashboardPreferenciasRoute: DashboardPreferenciasRoute,
  DashboardRobotRoute: DashboardRobotRoute,
  DashboardSeguridadRoute: DashboardSeguridadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
